export const CHANGE_BG = `CHANGE_BG`;
export const CHANGE_READER_BG = `CHANGE_READER_BG`;
export const CHANGE_READER_COLOR = `CHANGE_READER_COLOR`;
export const CHANGE_READER_FONT = `CHANGE_READER_FONT`;
export const CHANGE_LINE_HEIGHT = `CHANGE_LINE_HEIGHT`;
export const CHANGE_LETTER_SPACING = `CHANGE_LETTER_SPACING`;